#!/bin/bash
#mshsort is a small utility that reads a Gmsh mesh file and makes the numbering
# dense (without gaps in the node/element number sequences)

#this script just sorts the file $1 "inplace"

#the program is in gmsh-1.56.3/utils/misc/mshsort.cpp
#compile using:
#g++ -o mshsort mshsort.cpp

src/mesh/mshsort.orig $1 $1.tmp && mv $1.tmp $1
