#! /usr/bin/env python

import numpy

from femlib import System

s=System("tmp/in.xda", "tmp/matrices", "tmp/t12.boundaries")
s.compute_element_matrices()
s.assemble()
sol=s.solve()
grad=s.gradient(sol)
graintop=s.integ(grad,1)
othertop=s.integ(grad,3)
sides=s.integ(grad,4)
substrate=s.integ(grad,2)

g=numpy.sqrt(grad[0]**2+grad[1]**2+grad[2]**2)
s.save("tmp/sol.h5", sol, g)

print "results:"
print "grain top:",graintop
print "other top:",othertop
print "sides    :",sides
print "substrate:",substrate
print "----- total -----"
print "top      :",graintop+othertop
print "top+sides:",graintop+othertop+sides
print "all      :",graintop+othertop+sides+substrate
