#! /usr/bin/env python

import sys; sys.path.append("/home/ondra/femgeom")

import pexpect

import geom

meshgeometry="meshes/t.geo"

pexpect.run("gmsh -0 %s -o tmp/x.geo"%(meshgeometry))
g=geom.read_gmsh("tmp/x.geo")
g.printinfo()
geom.write_tetgen(g,"tmp/t.poly")
#geom.runtetgen("/home/ondra/femgeom/tetgen/tetgen","tmp/t.poly",a=0.0001,Q=0.8)
#geom.runtetgen("/home/ondra/femgeom/tetgen/tetgen","tmp/t.poly",a=0.00001,Q=0.8)
geom.runtetgen("/home/ondra/femgeom/tetgen/tetgen","tmp/t.poly",a=0.001,Q=0.8)
m=geom.read_tetgen("tmp/t.1")
m.printinfo()
m.writemsh("tmp/t12.msh")
m.writexda("tmp/in.xda")
m.writeregions("tmp/t12.regions")
m.writeBC("tmp/t12.boundaries")
