#! /bin/bash
order=1
file=t1

#gmsh t1.geo -2 -order $order
gmsh meshes/$file.geo -o tmp/$file.msh -3 -order $order
#gmsh t1.geo -3 -order $order 2>/dev/null&&
src/mesh/mshsort tmp/$file.msh 
src/mesh/msh2libmesh 
