#! /usr/bin/env python

from femlib import System

s=System("tmp/in.xda", "tmp/matrices", "tmp/t12.boundaries",
        "tmp/sol.h5")
s.compute_element_matrices()
s.assemble()
s.solve()
s.gradient()
s.integ()
s.save()

print "done."
