#! /usr/bin/env python

from femlib import System

s=System("tmp/in.xda", "tmp/matrices", "tmp/t12.boundaries")
s.compute_element_matrices()
s.assemble()
sol=s.solve()
grad=s.gradient(sol)
print s.integ(grad,1)+s.integ(grad,3)
print s.integ(grad,2)

s.save("tmp/sol.h5", sol, grad)

print "done."
