#! /bin/bash

#src/solver-pysparse/solve.py
#src/solver-petsc/solver -f1 ../../tmp/matA.petsc -f2 ../../tmp/matM.petsc -eps_nev 4
#mpirun -np 1 src/solver-petsc/solver -f1 ../../tmp/matA.petsc -f2 ../../tmp/vecF.petsc 
mpirun -np 1 src/solver-petsc/solver -f1 tmp/matA.petsc -f2 tmp/vecF.petsc 

#src/mesh/gmv2pos 
#gzip -f tmp/sol.pos
